import {
  BadRequestException,
  Body,
  Controller,
  DefaultValuePipe,
  Get,
  Headers,
  Param,
  ParseIntPipe,
  Post,
  Query,
  Request,
  UseGuards,
} from '@nestjs/common';
import {
  ApiBearerAuth,
  ApiHeader,
  ApiOperation,
  ApiTags,
} from '@nestjs/swagger';
import { RouteConfig } from '@nestjs/platform-fastify';

import { JwtAuthGuard } from '../auth/guards/jwt-auth.guard';
import { OptionalJwtAuthGuard } from '../auth/guards/optional-jwt-auth.guard';
import { CreateOrderDto } from './dto/orders.dto';
import { OrdersService } from './orders.service';

type AuthenticatedUser = {
  id: string;
  email: string;
  role: 'customer' | 'admin' | 'super_admin';
};

type RequestWithOptionalUser = {
  user?: AuthenticatedUser;
};

const UUID_PATTERN =
  /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;

@ApiTags('Orders')
@Controller('orders')
export class OrdersController {
  constructor(
    private readonly ordersService: OrdersService,
  ) {}

  @Post()
  @RouteConfig({
    rateLimit: {
      max: 10,
      timeWindow: '10 minutes',
    },
  })
  @UseGuards(OptionalJwtAuthGuard)
  @ApiHeader({
    name: 'Idempotency-Key',
    required: true,
    description:
      'Unique key generated by the frontend for this checkout attempt.',
  })
  @ApiHeader({
    name: 'X-Session-Id',
    required: false,
    description:
      'Required for guest checkout. Use the same guest session id as the cart.',
  })
  @ApiOperation({
    summary:
      'Create a new order safely (guest or authenticated checkout)',
  })
  async createOrder(
    @Request() req: RequestWithOptionalUser,
    @Body() body: CreateOrderDto,
    @Headers('idempotency-key')
    idempotencyKey?: string,
    @Headers('x-session-id')
    sessionIdHeader?: string,
  ) {
    const key = idempotencyKey?.trim();

    if (!key) {
      throw new BadRequestException(
        'Idempotency-Key header is required',
      );
    }

    let sessionId: string | undefined;

    if (!req.user) {
      sessionId = sessionIdHeader?.trim();

      if (!sessionId || !UUID_PATTERN.test(sessionId)) {
        throw new BadRequestException(
          'Guest checkout requires a valid X-Session-Id',
        );
      }
    }

    return this.ordersService.createIdempotent(
      {
        userId: req.user?.id,
        ...body,
      },
      {
        key,
        sessionId,
      },
    );
  }

  @Get()
  @UseGuards(JwtAuthGuard)
  @ApiBearerAuth()
  @ApiOperation({ summary: 'Get my orders' })
  async getMyOrders(
    @Request() req: RequestWithOptionalUser,
    @Query(
      'page',
      new DefaultValuePipe(1),
      ParseIntPipe,
    )
    page: number,
    @Query(
      'limit',
      new DefaultValuePipe(10),
      ParseIntPipe,
    )
    limit: number,
  ) {
    return this.ordersService.findByUserId(
      req.user!.id,
      page,
      limit,
    );
  }

  @Get(':reference')
  @UseGuards(OptionalJwtAuthGuard)
  @ApiBearerAuth()
  @ApiHeader({
    name: 'X-Order-Access-Token',
    required: false,
    description:
      'Required for guest orders. Returned once when the guest order is created.',
  })
  @ApiOperation({
    summary:
      'Get an order by reference using account ownership or guest access token',
  })
  async getByReference(
    @Param('reference') reference: string,
    @Request() req: RequestWithOptionalUser,
    @Headers('x-order-access-token')
    guestAccessToken?: string,
  ) {
    return this.ordersService.findByReference(
      reference,
      req.user?.id,
      guestAccessToken?.trim() || undefined,
    );
  }
}
